CREATE TABLE events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  event_date DATE NOT NULL,
  place VARCHAR(255),
  memo TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
